{"name": "test_enterDataInForm", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <AppiumFrameWork.tests.LoginTest.LoginTest testMethod=test_enterDataInForm>\n\n    @pytest.fixture(autouse=True)\n    def classObjects(self):\n        self.gt = LoginPage(self.driver)\n>       self.bp = BasePage(self.driver)\nE       TypeError: 'module' object is not callable\n\nLoginTest.py:12: TypeError"}, "attachments": [{"name": "stdout", "source": "559a9443-4afe-429c-928f-3ddc4991959a-attachment.txt", "type": "text/plain"}], "start": 1717654972599, "stop": 1717654972599, "uuid": "3c07f5d4-e083-44e1-986d-2a4671385334", "historyId": "591f628c01fccf2f827951e271155f7c", "testCaseId": "591f628c01fccf2f827951e271155f7c", "fullName": "LoginTest.LoginTest#test_enterDataInForm", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-J53686U"}, {"name": "thread", "value": "3020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}