{"name": "test_LoginFailMethod", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <AppiumFrameWork.tests.LoginTest.LoginTest testMethod=test_LoginFailMethod>\n\n    @pytest.fixture(autouse=True)\n    def classObjects(self):\n        self.gt = LoginPage(self.driver)\n>       self.bp = BasePage(self.driver)\nE       TypeError: 'module' object is not callable\n\nLoginTest.py:12: TypeError"}, "attachments": [{"name": "stdout", "source": "ab9e4138-2d44-4614-b238-3c62b2b3f75d-attachment.txt", "type": "text/plain"}], "start": 1717654962712, "stop": 1717654962712, "uuid": "74ea004f-72d5-4991-86ed-c4757cfd9d33", "historyId": "65a81de18a839901109845f7f191bb0f", "testCaseId": "65a81de18a839901109845f7f191bb0f", "fullName": "LoginTest.LoginTest#test_LoginFailMethod", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-J53686U"}, {"name": "thread", "value": "3020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}